version: '3.3'

services:

  db:
    env_file:
      - .env
    container_name: depremdb
    image: postgres:11-alpine
    expose:
      - "5432"
    ports:
      - "5454:5432"
    volumes:
      - /temp/data/deprem1:/var/lib/postgresql/data:rw

  web:
    build: .
    image: deprem_web
    env_file:
      - .env
    container_name: deprem
    volumes:
      - .:/code/deprem
    depends_on:
      - db
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/8c0f14ed4a6c9fb9.crt:/etc/nginx/ssl/live/audteye.com/fullchain.pem
      - ./nginx/certs/secret.key:/etc/nginx/ssl/live/audteye.com/privkey.pem
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
      - ./templates:/code/templates
    depends_on:
      - web