# Generated by Django 4.1.6 on 2023-02-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ihbar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IhbarUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ihbar_first_name", models.CharField(max_length=100)),
                ("ihbar_last_name", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=100)),
                ("eposta", models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KayipUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kayip_first_name", models.CharField(max_length=100)),
                ("kayip_last_name", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=100)),
                ("cordinate_x", models.FloatField(max_length=10)),
                ("cordinate_y", models.FloatField(max_length=10)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="tags",
            field=models.ManyToManyField(to="appname.tag"),
        ),
        migrations.AddField(
            model_name="ihbar",
            name="ihbar_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appname.ihbaruser"
            ),
        ),
        migrations.AddField(
            model_name="ihbar",
            name="kayip_user",
            field=models.ManyToManyField(to="appname.kayipuser"),
        ),
    ]
