# Generated by Django 4.1.6 on 2023-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihbar',
            name='access_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
