# Generated by Django 4.1.6 on 2023-02-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kayipuser",
            name="kayip_phone_number",
        ),
    ]
