# Generated by Django 4.1.6 on 2023-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
