# Generated by Django 4.1.6 on 2023-02-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0002_remove_kayipuser_kayip_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="KayipStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="kayip_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appname.kayipstatus",
            ),
        ),
    ]
