# Generated by Django 4.1.6 on 2023-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_ihbar_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihbar',
            name='access_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
