# Generated by Django 4.1.6 on 2023-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0002_ihbar_ihbaruser_kayipuser_tag_delete_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kayipuser",
            name="tags",
            field=models.ManyToManyField(blank=True, to="appname.tag"),
        ),
    ]
