# Generated by Django 4.1.6 on 2023-02-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0003_kayipstatus_kayipuser_kayip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kayipuser",
            name="kayip_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kayiplar",
                to="appname.kayipstatus",
            ),
        ),
    ]
