# Generated by Django 4.1.6 on 2023-02-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayipuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.cities'),
        ),
    ]
