# Generated by Django 4.1.6 on 2023-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_ihbar_access_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ihbar',
            options={'verbose_name': 'Ihbar', 'verbose_name_plural': 'Ihbarlar'},
        ),
        migrations.AlterModelOptions(
            name='ihbaruser',
            options={'verbose_name': 'Ihbar Eden Kişiler', 'verbose_name_plural': 'Ihbar Eden Kişiler'},
        ),
        migrations.AlterModelOptions(
            name='kayipuser',
            options={'verbose_name': 'Kaybolan Kişiler', 'verbose_name_plural': 'Kaybolan Kişiler'},
        ),
    ]
