# Generated by Django 4.1.6 on 2023-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0003_alter_kayipuser_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ihbar",
            name="detail",
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
