# Generated by Django 4.1.6 on 2023-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0004_remove_ihbar_detail_kayipuser_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kayipuser",
            name="cordinate_x",
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="cordinate_y",
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="appname.tag"),
        ),
    ]
