# Generated by Django 4.1.6 on 2023-02-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_alter_ihbar_options_alter_ihbaruser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagArabic',
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Ülkeler', 'verbose_name_plural': 'Ülkeler'},
        ),
        migrations.AlterModelOptions(
            name='kayipstatus',
            options={'verbose_name': 'Kayıp Durumları', 'verbose_name_plural': 'Kayıp Durumları'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tagler', 'verbose_name_plural': 'Tagler'},
        ),
    ]
