# Generated by Django 4.1.6 on 2023-02-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_kayipuser_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Şehirler', 'verbose_name_plural': 'Şehirler'},
        ),
        migrations.AddField(
            model_name='countries',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
