# Generated by Django 4.1.6 on 2023-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_delete_tagarabic_alter_countries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihbar',
            name='created_time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='kayipuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
