# Generated by Django 4.1.6 on 2023-02-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_countries_ihbaruser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihbaruser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='kayipuser',
            name='kayip_status',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='KayipStatus',
        ),
    ]
