# Generated by Django 4.1.6 on 2023-02-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_alter_cities_options_countries_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihbaruser',
            name='country',
        ),
    ]
