# Generated by Django 4.1.6 on 2023-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0005_alter_kayipuser_cordinate_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kayipuser",
            name="cordinate_x",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="cordinate_y",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
