# Generated by Django 4.1.6 on 2023-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_ihbar_created_time_kayipuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayipuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
