# Generated by Django 4.1.6 on 2023-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_kayipuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihbar',
            name='created_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
