# Generated by Django 4.1.6 on 2023-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0007_alter_ihbar_ihbar_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagArabic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="ihbaruser",
            name="eposta",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="tags",
            field=models.ManyToManyField(blank=True, to="appname.tag"),
        ),
    ]
