# Generated by Django 4.1.6 on 2023-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_alter_ihbar_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='kayip_first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
