# Generated by Django 4.1.6 on 2023-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0008_tagarabic_alter_ihbaruser_eposta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kayipuser",
            name="found",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
