# Generated by Django 4.1.6 on 2023-02-11 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_kayipuser_kayip_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayipuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
