# Generated by Django 4.1.6 on 2023-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0009_kayipuser_found"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kayipuser",
            name="found",
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
