# Generated by Django 4.1.6 on 2023-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0009_kayipuser_found"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kayipuser",
            name="found",
        ),
        migrations.RemoveField(
            model_name="kayipuser",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="kayipuser",
            name="tags",
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="kayip_phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
