# Generated by Django 4.1.6 on 2023-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appname",
            "0010_remove_kayipuser_found_remove_kayipuser_phonenumber_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kayipuser",
            name="tags",
            field=models.ManyToManyField(blank=True, to="appname.tag"),
        ),
    ]
