# Generated by Django 4.1.6 on 2023-02-11 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_kayipuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
