# Generated by Django 4.1.6 on 2023-02-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0010_remove_kayipuser_found_kayipuser_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kayipuser",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="kayipuser",
            name="kayip_phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="kayipuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
