# Generated by Django 4.1.6 on 2023-02-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_remove_kayipuser_found_kayipuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kayipuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
