# Generated by Django 4.1.6 on 2023-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_alter_kayipuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='age',
            field=models.CharField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
