# Generated by Django 4.1.6 on 2023-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_alter_kayipuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayipuser',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
